Condition:
        type: object
        config:
            fields:
                text:
                    type: 'String'
                code:
                    type: 'Int'
                temperature:
                    type: 'Int'