Observation:
        type: object
        config:
            fields:
                city:
                    type: 'String'
                wind:
                    type: 'Wind'
                atmosphere:
                    type: 'Atmosphere'
                astronomy:
                    type: 'Astronomy'
                condition:
                    type: 'Condition'